config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'tanks/new'
  get 'tanks/create'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'signup', to: 'email_signup#show'
  post 'signup', to: 'email_signup#create'
  get 'users/profile', to: 'users/profile#profile'
  put 'users/profile', to: 'users/profile#profile_update'
  resources :users, only: %i[edit update] do
    resources :follows, module: :users, only: %i[create destroy]
  end
  resources :tanks do
    resources :parameters, module: :tanks
    resources :equipments, module: :tanks
    resources :heaters, module: :tanks
    resources :lights, module: :tanks
    resources :pumps, module: :tanks
    resources :livestocks, module: :tanks
    resources :fish, module: :tanks
    resources :corals, module: :tanks
    resources :invertebrates, module: :tanks
    delete 'remove_image/:image_id', to: 'tanks#remove_image', as: 'remove_image'
  end
  resources :user_tanks, only: [:index]
  get 'up', to: proc { [200, {}, ['OK']] }
end

app/models/livestock.rb
class Livestock < ApplicationRecord
  has_one_attached :image
  belongs_to :tank

  delegated_type :livestockable, types: %w[Fish Invertebrate Coral]

  scope :fish, -> { where(livestockable_type: 'Livestocks::Fish') }
  scope :invertebrates, -> { where(livestockable_type: 'Livestocks::Invertebrate') }
  scope :coral, -> { where(livestockable_type: 'Livestocks::Coral') }

  def turbo_frame_tag
    prefix = "livestock_#{type}_"
    suffix = id.present? ? id : 'new'

    "#{prefix}#{suffix}"
  end

  def type
    livestockable_type.demodulize.underscore
  end
end

app/models/livestocks/Invertebrate.rb
module Livestocks
  class Invertebrate < ApplicationRecord
    include Livestockable
  end
end

app/models/livestocks/coral.rb
module Livestocks
  class Coral < ApplicationRecord
    include Livestockable

    enum coral_type: {
      lps: 0,                # Large Polyp Stony
      sps: 1,                # Small Polyp Stony
      soft: 2,               # Soft Corals
      nps: 3,                # Non-Photosynthetic Corals
      mushroom: 4,           # Mushroom Corals
      gorgonian: 5,          # Gorgonians
      encrusting: 6,         # Encrusting Corals
      zoanthid: 7,           # Zoanthids
      leather: 8,            # Leather Corals
      plate: 9,              # Plate Corals
      branching: 10,         # Branching Corals
      foliose: 11,           # Foliose Corals
      massive: 12,           # Massive Corals
      free_living: 13        # Free-Living Corals
    }
  end
end

app/models/livestocks/fish.rb
module Livestocks
  class Fish < ApplicationRecord
    include Livestockable
  end
end

app/models/tank.rb
# frozen_string_literal: true

class Tank < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :tank_parameters
  has_many :equipment
  has_many :livestocks

  measured Measured::Volume, :total_volume
  measured Measured::Volume, :display_volume
  measured Measured::Volume, :sub_volume
  measured Measured::Length, :glass_thickness

  validates :name, :description, presence: true

  def update_with_attachments(params)
    images.attach(params[:images]) if params[:images].present?

    if params[:image_ids].present?
      images.each do |image|
        image.purge unless params[:image_ids].include?(image.id.to_s)
      end
    end

    update(params.except(:images, :image_ids))
  end
end

app/controllers/tanks/corals_controller.rb
# frozen_string_literal: true

module Tanks
  class CoralsController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def perform_create_action(livestock)
      livestock.livestockable.update(coral_type: params[:livestock][:coral_type]) if params[:livestock][:coral_type]
    end

    def perform_edit_action(livestock)
      livestock.livestockable.update(coral_type: params[:livestock][:coral_type]) if params[:livestock][:coral_type]
    end

    def set_new_livestock
      @livestock = @tank.livestocks.coral.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Coral.new
    end
  end
end

app/controllers/tanks/equipments_base_controller.rb
# frozen_string_literal: true

module Tanks
  class EquipmentsBaseController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :set_equipment, only: %i[edit update destroy]

    def create
      if @equipment.save
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.append(@equipment.type.pluralize, partial: 'tanks/equipments/equipment',
                                                             locals: { equipment: @equipment,
                                                                       include_manage_buttons: true }),
              turbo_stream.update(
                @tank.equipment.new(equipmentable: @equipment.equipmentable_type.constantize.new).turbo_frame_tag, ''
              )
            ]
          end
          format.html { redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully created.' }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @equipment.update(equipment_params)
        redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @equipment.destroy

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@equipment.turbo_frame_tag) }
        format.html { redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully destroyed.' }
      end
    end

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def equipment_params
      permitted_params = params[:equipment] ? params.require(:equipment) : params
      permitted_params.permit(:manufacturer, :title, :model, :quantity, :image).merge(tank_id: params[:tank_id])
    end

    def set_equipment
      @equipment = Equipment.find(params[:id])
    end
  end
end

app/controllers/tanks/equipments_controller.rb
# frozen_string_literal: true

module Tanks
  class EquipmentsController < EquipmentsBaseController
    before_action :authenticate_user!
    before_action :set_tank

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end
  end
end

app/controllers/tanks/fish_controller.rb
# frozen_string_literal: true

module Tanks
  class FishController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def set_new_livestock
      @livestock = @tank.livestocks.fish.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Fish.new
    end
  end
end

app/controllers/tanks/heaters_controller.rb
# frozen_string_literal: true

module Tanks
  class HeatersController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.heaters.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Heater.new
    end
  end
end

app/controllers/tanks/invertebrates_controller.rb
# frozen_string_literal: true

module Tanks
  class InvertebratesController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def set_new_livestock
      @livestock = @tank.livestocks.invertebrates.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Invertebrate.new
    end
  end
end

app/controllers/tanks/lights_controller.rb
# frozen_string_literal: true

module Tanks
  class LightsController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.lights.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Light.new
    end
  end
end

app/controllers/tanks/livestocks_base_controller.rb
# frozen_string_literal: true

module Tanks
  class LivestocksBaseController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :set_livestock, only: %i[edit update destroy]

    def create
      if @livestock.save
        perform_create_action(@livestock)
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.append(@livestock.type.pluralize, partial: 'tanks/livestocks/livestock',
                                                             locals: { livestock: @livestock,
                                                                       include_manage_buttons: true }),
              turbo_stream.update(
                @tank.livestocks.new(livestockable: @livestock.livestockable_type.constantize.new).turbo_frame_tag, ''
              )
            ]
          end
          format.html { redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully created.' }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @livestock.update(livestock_params)
        perform_update_action(@livestock)
        redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @livestock.destroy

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@livestock.turbo_frame_tag) }
        format.html { redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully destroyed.' }
      end
    end

    private

    def perform_create_action(livestock)
    end

    def perform_update_action(livestock)
    end

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def livestock_params
      permitted_params = params[:livestock] ? params.require(:livestock) : params
      permitted_params.permit(:name, :purchase_date, :quantity, :image).merge(tank_id: params[:tank_id])
    end

    def set_livestock
      @livestock = Livestock.find(params[:id])
    end
  end
end

app/controllers/tanks/livestocks_controller.rb
# frozen_string_literal: true

module Tanks
  class LivestocksController < LivestocksBaseController
    before_action :authenticate_user!
    before_action :set_tank

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end
  end
end

app/controllers/tanks/parameters_controller.rb
# frozen_string_literal: true

module Tanks
  class ParametersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :must_be_tank_owner!
    before_action :set_tank_parameter, only: [:destroy]

    def index
      @tank_parameters = @tank.tank_parameters.order(created_at: :desc)
      @new_tank_parameters = @tank.tank_parameters.new
    end

    def create
      @tank_parameters = @tank.tank_parameters.new(parameter_params)

      if @tank_parameters.save
        respond_to do |format|
          format.turbo_stream
        end
      else
        @new_tank_parameters = @tank_parameters
        @tank_parameters = @tank.tank_parameters.order(created_at: :desc)
        render :index, status: :unprocessable_entity
      end
    end

    def destroy
      @tank_parameter.destroy!

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@tank_parameter) }
      end
    end

    private

    def parameter_params
      params.require(:tank_parameter).permit(:date, :ph, :temp, :salinity, :alkalinity, :ammonia, :nitrite, :nitrate,
                                             :phosphate, :calcium, :magnesium)
    end

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def set_tank_parameter
      @tank_parameter = TankParameter.find(params[:id])
    end

    def must_be_tank_owner!
      return if @tank.user == Current.user

      head :forbidden
    end
  end
end

app/controllers/tanks/pumps_controller.rb
# frozen_string_literal: true

module Tanks
  class PumpsController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.pumps.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Pump.new
    end
  end
end

app/controllers/tanks_controller.rb
# frozen_string_literal: true

class TanksController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_tank, only: %i[show destroy edit update]

  def index
    @pagy, @tanks = pagy(Tank.all.order(created_at: :desc), items: 12)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @latest_parameters = @tank.tank_parameters.latest.first
  end

  def new
    @tank = Tank.new
  end

  def create
    @tank = Tank.new(tank_params)
    @tank.user_id = Current.user.id
    if @tank.save
      redirect_to user_tanks_path, notice: 'Tank was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @tank.destroy
    respond_to do |format|
      format.html { redirect_to user_tanks_path, notice: 'Tank was successfully destroyed.' }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@tank) }
    end
  end

  def update
    if @tank.update_with_attachments(tank_params)
      respond_to do |format|
        format.html { redirect_to edit_tank_path(@tank), notice: 'Tank was successfully updated.' }
      end
    else
      render :edit
    end
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @image.purge_later
    respond_to do |format|
      format.html { redirect_back(fallback_location: request.referrer) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove("image-#{@image.id}") }
    end
  end

  private

  def set_tank
    @tank = Tank.find(params[:id])
  end

  def tank_params
    params.require(:tank).permit(:name, :description, :total_volume_value, :total_volume_unit, :display_volume_value,
                                 :display_volume_unit, :sub_volume_value, :sub_volume_unit, :glass_thickness_value,
                                 :glass_thickness_unit, images: [], image_ids: []).tap do |permitted|
      permitted[:images]&.reject!(&:blank?)
    end
  end
end

app/helpers/tanks_helper.rb
# frozen_string_literal: true

module TanksHelper
  def volume_options
    [
      %w[Gallons us_gallon],
      %w[Liters l]
    ]
  end

  def thickness_options
    [
      %w[Inches in],
      %w[Millimeters mm]
    ]
  end

  def tank_live_stock_form_url(livestock)
    model = livestock.livestockable_type.demodulize.underscore
    suffix = model == 'fish' ? 'index_path' : 'path'

    if livestock.persisted?
      send("tank_#{model}_path", livestock.tank, livestock)
    else
      send("tank_#{model.pluralize}_#{suffix}", livestock.tank, livestock)
    end
  end

  def coral_type_options
    types = Livestocks::Coral.coral_types.map { |key, _| [key.titleize, key] }
    types.unshift(['Select a coral type', nil])
    types
  end
end

app/views/tanks/livestocks/_edit_livestock.html.erb
<div class="container">
  <%= link_to sanitize("&larr; Back to Tamk"), tank_livestocks_path(tank) %>

  <div class="header">
    <h1><%= title %></h1>
  </div>

  <%= turbo_frame_tag livestock.turbo_frame_tag do %>
    <%= render partial: 'tanks/livestocks/form', locals: { tank: tank, livestock: livestock } %>
  <% end %>
</div>

app/views/tanks/livestocks/_form.html.erb
<%= form_with(
      model: livestock,
      url: tank_live_stock_form_url(livestock),
      local: true,
      html: { class: 'space-y-6 p-4 bg-white rounded-lg shadow-md livestock-form mb-5' }
    ) do |f| %>
  <% if livestock.errors.any? %>
    <div class="p-3 mb-4 text-red-700 bg-red-100 border border-red-300 rounded-md">
      <%= livestock.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div>
    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :name, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
  </div>

  <div>
    <%= f.label :purchase_date, class: "block text-sm font-medium text-gray-700" %>
    <%= f.date_field :purchase_date, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
  </div>

  <div>
    <%= f.label :quantity, class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :quantity, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
  </div>

  <% if lookup_context.find_all("tanks/#{livestock.livestockable_type.demodulize.underscore.pluralize}/_extra_fields_form").any? %>
    <%= render "tanks/#{livestock.livestockable_type.demodulize.underscore.pluralize}/extra_fields_form", livestock: livestock, f: f %>
  <% end %>

  <div>
    <%= f.label :image, class: "block text-sm font-medium text-gray-700" %>
    <%= f.file_field :image, accept: 'image/*', class: "mt-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
  </div>

  <% if livestock.image.attached? %>
    <div class="relative">
      <%= image_tag livestock.image.variant(resize_to_limit: [150, 150]).processed, class: " rounded-lg shadow-md" %>
    </div>
  <% end %>

  <div>
    <%= f.submit 'Save', class: "inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-500 hover:to-indigo-700 sm:mb-0 sm:w-auto hover:bg-indigo-600 sm:rounded-full" %>
  </div>
<% end %>

app/views/tanks/livestocks/_new_livestock.html.erb
<div class="container">
  <%= link_to sanitize("&larr; Back to Tamk"), tank_livestocks_path(tank) %>

  <div class="header">
    <h1><%= title %></h1>
  </div>

  <%= turbo_frame_tag livestock_frame_tag do %>
    <%= render partial: 'tanks/livestocks/form', locals: { tank: tank, livestock: livestock } %>
  <% end %>
</div>

app/views/tanks/livestocks/index.html.erb
<div class="container mx-auto p-4">
  <%= render partial: 'shared/components/h1', locals: { title: 'Tank Livestock' } %>
  <div class="py-4"><%= link_to "← Back to Tank Edit", edit_tank_path(@tank), class: 'block w-full bg-gray-300 text-black px-4 py-2 rounded-lg hover:bg-gray-2000' %></div>

  <h2 class="text-xl md:text-2xl font-semibold text-gray-800 my-4">Fish</h2>
  <div id="<%= @tank.livestocks.fish.new.type.pluralize %>" class="mb-6">
    <% @tank.livestocks.fish.each do |fish| %>
      <%= render 'tanks/livestocks/livestock', livestock: fish, include_manage_buttons: true %>
    <% end %>
  </div>
  <%= turbo_frame_tag @tank.livestocks.fish.new.turbo_frame_tag %>

  <%= link_to 'Add Fish', new_tank_fish_path(@tank), class: 'inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-gray-400 to-gray-700 hover:from-gray-500 hover:to-gray-700 sm:mb-0 sm:w-auto hover:bg-gray-600 sm:rounded-full', data: { turbo_frame: @tank.livestocks.fish.new.turbo_frame_tag } %>

  <h2 class="text-xl md:text-2xl font-semibold text-gray-800 my-4">Invertebrates</h2>
  <div id="<%= @tank.livestocks.invertebrates.new.type.pluralize %>" class="mb-6">
    <% @tank.livestocks.invertebrates.each do |invertebrate| %>
      <%= render 'tanks/livestocks/livestock', livestock: invertebrate, include_manage_buttons: true %>
    <% end %>
  </div>
  <%= turbo_frame_tag @tank.livestocks.invertebrates.new.turbo_frame_tag %>

  <%= link_to 'Add Invertebrate', new_tank_invertebrate_path(@tank), class: 'inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-gray-400 to-gray-700 hover:from-gray-500 hover:to-gray-700 sm:mb-0 sm:w-auto hover:bg-gray-600 sm:rounded-full', data: { turbo_frame: @tank.livestocks.invertebrates.new.turbo_frame_tag } %>

  <h2 class="text-xl md:text-2xl font-semibold text-gray-800 my-4">Corals</h2>
  <div id="<%= @tank.livestocks.corals.new.type.pluralize %>" class="mb-6">
    <% @tank.livestocks.coral.each do |coral| %>
      <%= render 'tanks/livestocks/livestock', livestock: coral, include_manage_buttons: true %>
    <% end %>
  </div>
  <%= turbo_frame_tag @tank.livestocks.corals.new.turbo_frame_tag %>

  <%= link_to 'Add Coral', new_tank_coral_path(@tank), class: 'inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-gray-400 to-gray-700 hover:from-gray-500 hover:to-gray-700 sm:mb-0 sm:w-auto hover:bg-gray-600 sm:rounded-full', data: { turbo_frame: @tank.livestocks.corals.new.turbo_frame_tag } %>
</div>

app/views/tanks/livestocks/new.html.erb
<div class="container">
  <%= link_to sanitize("&larr; Back to Tamk"), tank_livestocks_path(@tank) %>

  <%= render partial: 'tanks/livestocks/form', locals: { tank: @tank, livestock: @livestock } %>
</div>