config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'tanks/new'
  get 'tanks/create'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'signup', to: 'email_signup#show'
  post 'signup', to: 'email_signup#create'
  get 'users/profile', to: 'users/profile#profile'
  put 'users/profile', to: 'users/profile#profile_update'
  resources :users, only: %i[edit update] do
    resources :follows, module: :users, only: %i[create destroy]
  end
  resources :tanks do
    resources :parameters, module: :tanks
    resources :equipments, module: :tanks
    resources :heaters, module: :tanks
    resources :lights, module: :tanks
    resources :pumps, module: :tanks
    resources :livestocks, module: :tanks
    resources :fish, module: :tanks
    resources :corals, module: :tanks
    resources :invertebrates, module: :tanks
    delete 'remove_image/:image_id', to: 'tanks#remove_image', as: 'remove_image'
  end
  resources :user_tanks, only: [:index]
  get 'up', to: proc { [200, {}, ['OK']] }
end

app/models/tank.rb
# frozen_string_literal: true

class Tank < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :tank_parameters
  has_many :equipment
  has_many :livestocks

  measured Measured::Volume, :total_volume
  measured Measured::Volume, :display_volume
  measured Measured::Volume, :sub_volume
  measured Measured::Length, :glass_thickness

  validates :name, :description, presence: true

  def update_with_attachments(params)
    images.attach(params[:images]) if params[:images].present?

    if params[:image_ids].present?
      images.each do |image|
        image.purge unless params[:image_ids].include?(image.id.to_s)
      end
    end

    update(params.except(:images, :image_ids))
  end
end

app/controllers/tanks/corals_controller.rb
# frozen_string_literal: true

module Tanks
  class CoralsController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def perform_create_action(livestock)
      livestock.livestockable.update(coral_type: params[:livestock][:coral_type]) if params[:livestock][:coral_type]
    end

    def perform_edit_action(livestock)
      livestock.livestockable.update(coral_type: params[:livestock][:coral_type]) if params[:livestock][:coral_type]
    end

    def set_new_livestock
      @livestock = @tank.livestocks.coral.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Coral.new
    end
  end
end

app/controllers/tanks/equipments_base_controller.rb
# frozen_string_literal: true

module Tanks
  class EquipmentsBaseController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :set_equipment, only: %i[edit update destroy]

    def create
      if @equipment.save
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.append(@equipment.type.pluralize, partial: 'tanks/equipments/equipment',
                                                             locals: { equipment: @equipment,
                                                                       include_manage_buttons: true }),
              turbo_stream.update(
                @tank.equipment.new(equipmentable: @equipment.equipmentable_type.constantize.new).turbo_frame_tag, ''
              )
            ]
          end
          format.html { redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully created.' }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @equipment.update(equipment_params)
        redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @equipment.destroy

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@equipment.turbo_frame_tag) }
        format.html { redirect_to tank_equipments_path(@tank), notice: 'Equipment was successfully destroyed.' }
      end
    end

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def equipment_params
      permitted_params = params[:equipment] ? params.require(:equipment) : params
      permitted_params.permit(:manufacturer, :title, :model, :quantity, :image).merge(tank_id: params[:tank_id])
    end

    def set_equipment
      @equipment = Equipment.find(params[:id])
    end
  end
end

app/controllers/tanks/equipments_controller.rb
# frozen_string_literal: true

module Tanks
  class EquipmentsController < EquipmentsBaseController
    before_action :authenticate_user!
    before_action :set_tank

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end
  end
end

app/controllers/tanks/fish_controller.rb
# frozen_string_literal: true

module Tanks
  class FishController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def set_new_livestock
      @livestock = @tank.livestocks.fish.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Fish.new
    end
  end
end

app/controllers/tanks/heaters_controller.rb
# frozen_string_literal: true

module Tanks
  class HeatersController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.heaters.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Heater.new
    end
  end
end

app/controllers/tanks/invertebrates_controller.rb
# frozen_string_literal: true

module Tanks
  class InvertebratesController < LivestocksBaseController
    before_action :set_new_livestock, only: %i[new]
    before_action :set_create_livestock, only: %i[create]

    private

    def set_new_livestock
      @livestock = @tank.livestocks.invertebrates.new
    end

    def set_create_livestock
      @livestock = @tank.livestocks.new(livestock_params)
      @livestock.livestockable = Livestocks::Invertebrate.new
    end
  end
end

app/controllers/tanks/lights_controller.rb
# frozen_string_literal: true

module Tanks
  class LightsController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.lights.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Light.new
    end
  end
end

app/controllers/tanks/livestocks_base_controller.rb
# frozen_string_literal: true

module Tanks
  class LivestocksBaseController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :set_livestock, only: %i[edit update destroy]

    def create
      if @livestock.save
        perform_create_action(@livestock)
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.append(@livestock.type.pluralize, partial: 'tanks/livestocks/livestock',
                                                             locals: { livestock: @livestock,
                                                                       include_manage_buttons: true }),
              turbo_stream.update(
                @tank.livestocks.new(livestockable: @livestock.livestockable_type.constantize.new).turbo_frame_tag, ''
              )
            ]
          end
          format.html { redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully created.' }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @livestock.update(livestock_params)
        perform_update_action(@livestock)
        redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @livestock.destroy

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@livestock.turbo_frame_tag) }
        format.html { redirect_to tank_livestocks_path(@tank), notice: 'Livestock was successfully destroyed.' }
      end
    end

    private

    def perform_create_action(livestock)
    end

    def perform_update_action(livestock)
    end

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def livestock_params
      permitted_params = params[:livestock] ? params.require(:livestock) : params
      permitted_params.permit(:name, :purchase_date, :quantity, :image).merge(tank_id: params[:tank_id])
    end

    def set_livestock
      @livestock = Livestock.find(params[:id])
    end
  end
end

app/controllers/tanks/livestocks_controller.rb
# frozen_string_literal: true

module Tanks
  class LivestocksController < LivestocksBaseController
    before_action :authenticate_user!
    before_action :set_tank

    private

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end
  end
end

app/controllers/tanks/parameters_controller.rb
# frozen_string_literal: true

module Tanks
  class ParametersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tank
    before_action :must_be_tank_owner!
    before_action :set_tank_parameter, only: [:destroy]

    def index
      @tank_parameters = @tank.tank_parameters.order(created_at: :desc)
      @new_tank_parameters = @tank.tank_parameters.new
    end

    def create
      @tank_parameters = @tank.tank_parameters.new(parameter_params)

      if @tank_parameters.save
        respond_to do |format|
          format.turbo_stream
        end
      else
        @new_tank_parameters = @tank_parameters
        @tank_parameters = @tank.tank_parameters.order(created_at: :desc)
        render :index, status: :unprocessable_entity
      end
    end

    def destroy
      @tank_parameter.destroy!

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@tank_parameter) }
      end
    end

    private

    def parameter_params
      params.require(:tank_parameter).permit(:date, :ph, :temp, :salinity, :alkalinity, :ammonia, :nitrite, :nitrate,
                                             :phosphate, :calcium, :magnesium)
    end

    def set_tank
      @tank = Tank.find(params[:tank_id])
    end

    def set_tank_parameter
      @tank_parameter = TankParameter.find(params[:id])
    end

    def must_be_tank_owner!
      return if @tank.user == Current.user

      head :forbidden
    end
  end
end

app/controllers/tanks/pumps_controller.rb
# frozen_string_literal: true

module Tanks
  class PumpsController < EquipmentsBaseController
    before_action :set_new_equipment, only: %i[new]
    before_action :set_create_equipment, only: %i[create]

    private

    def set_new_equipment
      @equipment = @tank.equipment.pumps.new
    end

    def set_create_equipment
      @equipment = @tank.equipment.new(equipment_params)
      @equipment.equipmentable = Equipments::Pump.new
    end
  end
end

app/controllers/tanks_controller.rb
# frozen_string_literal: true

class TanksController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_tank, only: %i[show destroy edit update]

  def index
    @pagy, @tanks = pagy(Tank.all.order(created_at: :desc), items: 12)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @latest_parameters = @tank.tank_parameters.latest.first
  end

  def new
    @tank = Tank.new
  end

  def create
    @tank = Tank.new(tank_params)
    @tank.user_id = Current.user.id
    if @tank.save
      redirect_to user_tanks_path, notice: 'Tank was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @tank.destroy
    respond_to do |format|
      format.html { redirect_to user_tanks_path, notice: 'Tank was successfully destroyed.' }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@tank) }
    end
  end

  def update
    if @tank.update_with_attachments(tank_params)
      respond_to do |format|
        format.html { redirect_to edit_tank_path(@tank), notice: 'Tank was successfully updated.' }
      end
    else
      render :edit
    end
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @image.purge_later
    respond_to do |format|
      format.html { redirect_back(fallback_location: request.referrer) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove("image-#{@image.id}") }
    end
  end

  private

  def set_tank
    @tank = Tank.find(params[:id])
  end

  def tank_params
    params.require(:tank).permit(:name, :description, :total_volume_value, :total_volume_unit, :display_volume_value,
                                 :display_volume_unit, :sub_volume_value, :sub_volume_unit, :glass_thickness_value,
                                 :glass_thickness_unit, images: [], image_ids: []).tap do |permitted|
      permitted[:images]&.reject!(&:blank?)
    end
  end
end

app/helpers/tanks_helper.rb
# frozen_string_literal: true

module TanksHelper
  def volume_options
    [
      %w[Gallons us_gallon],
      %w[Liters l]
    ]
  end

  def thickness_options
    [
      %w[Inches in],
      %w[Millimeters mm]
    ]
  end

  def tank_live_stock_form_url(livestock)
    model = livestock.livestockable_type.demodulize.underscore
    suffix = model == 'fish' ? 'index_path' : 'path'

    if livestock.persisted?
      send("tank_#{model}_path", livestock.tank, livestock)
    else
      send("tank_#{model.pluralize}_#{suffix}", livestock.tank, livestock)
    end
  end

  def coral_type_options
    types = Livestocks::Coral.coral_types.map { |key, _| [key.titleize, key] }
    types.unshift(['Select a coral type', nil])
    types
  end
end

app/views/tanks/_form.html.erb
<%= form_with(model: tank, local: true, class: 'w-full') do |form| %>
  <%= render 'shared/errors', resource: tank %>

  <div class="mb-6">
    <%= form.label :name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
    <%= form.text_field :name, class: "appearance-none block w-full text-gray-700 border  border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
  </div>
  <div class="mb-6">
    <%= form.label :description, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
    <%= form.text_area :description, class: "appearance-none block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
  </div>
  <div class="flex flex-wrap mb-6 mt-3">
    <div class="w-full md:w-1/2 px-0 mb-6 md:mb-0">
      <%= form.label :total_volume, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <div class="flex">
        <%= form.text_field :total_volume_value, type: :number, step: :any, class: "appearance-none block w-full text-gray-700 border border-gray-200 rounded-l py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
        <%= form.select :total_volume_unit, options_for_select(volume_options), class: "appearance-none border border-gray-200 text-gray-700 py-3 px-4 rounded-r leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
      </div>
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <%= form.label :display_volume, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <div class="flex">
        <%= form.text_field :display_volume_value, type: :number, step: :any, class: "appearance-none block w-full text-gray-700 border border-gray-200 rounded-l py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
        <%= form.select :display_volume_unit, options_for_select(volume_options), class: "appearance-none border border-gray-200 text-gray-700 py-3 px-4 rounded-r leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
      </div>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <%= form.label :sub_volume, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <div class="flex">
        <%= form.text_field :sub_volume_value, type: :number, step: :any, class: "appearance-none block w-full text-gray-700 border border-gray-200 rounded-l py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
        <%= form.select :sub_volume_unit, options_for_select(volume_options), class: "appearance-none border border-gray-200 text-gray-700 py-3 px-4 rounded-r leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
      </div>
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <%= form.label :glass_thickness, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <div class="flex">
        <%= form.text_field :glass_thickness_value, type: :number, step: :any, class: "appearance-none block w-full text-gray-700 border border-gray-200 rounded-l py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
        <%= form.select :glass_thickness_unit, options_for_select(thickness_options), class: "appearance-none border border-gray-200 text-gray-700 py-3 px-4 rounded-r leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
      </div>
    </div>
  </div>
  <div class="w-full mb-6">
    <div data-controller="multi-upload" data-multi-upload-image-width-value="150" data-multi-upload-image-height-value="150">
      <div class="photos">
        <%= form.label :images, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <% if tank.images.count < 5 %>
          <%= form.file_field :images, multiple: true, accept: 'image/*', direct_upload: true, data: { action: "multi-upload#addFile", multi_upload_target: "input" }, class: "block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-indigo-500" %>
        <% end %>
      </div>
      <div data-multi-upload-target="files" class="hidden"></div>

      <div class="existing-images flex flex-wrap gap-4" data-multi-upload-target="preview">
        <% tank.images.each do |image| %>
          <div id="image-<%= image.id =%>" class="relative">
            <%= image_tag image.variant(resize_to_limit: [150, 150]).processed, class: "w-full h-full object-cover rounded-lg shadow-md" %>
            <%= link_to 'Delete', tank_remove_image_path(tank.id, image), data: { turbo_method: :delete }, class: 'absolute right-0 top-0 bg-red-500 text-white p-1 rounded hover:bg-blue-800 m-1 text-xs' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="flex flex-wrap -mx-3 mb-2">
    <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
      <%= form.submit "Submit", class: "inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-500 hover:to-indigo-700 sm:mb-0 sm:w-auto hover:bg-indigo-600 sm:rounded-full" %>
    </div>
  </div>

  <hr class="my-5" />
<% end %>

app/views/tanks/_load_more_button.html.erb
 <% if @pagy.next.present? %>
    <%= button_to "Load more", tanks_path,
      params: { page: @pagy.next },
      method: :get,
      class: "inline-flex justify-center items-center w-full px-20 py-2 text-xl font-bold text-white bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-500 hover:to-indigo-700 sm:mb-0 sm:w-auto hover:bg-indigo-600 sm:rounded-full",
      "data-turbo-stream": true,
      "data-turbo-submits-with": "Loading..." %>
  <% end %>

app/views/tanks/_slideshow.html.erb
<div class="mt-8"  data-controller="slideshow">
  <div class="relative w-full overflow-hidden rounded-lg shadow-lg">
    <div id="slideshow" class="flex transition-transform duration-700 ease-in-out"  style="transform: translateX(0);" data-slideshow-target="slideshow">
      <% tank.images.each do |image| %>
        <%= image_tag url_for(image), class: "w-full object-cover h-48 md:h-64 flex-shrink-0 flex-grow-0", data: { action: "click->slideshow#showImage" , url_value: url_for(image) } %>
      <% end %>
    </div>

    <button id="prev" data-action="slideshow#prev" class="absolute left-2 top-1/2 transform -translate-y-1/2 bg-white bg-opacity-50 hover:bg-opacity-75 text-gray-800 font-bold py-2 px-4 rounded-full focus:outline-none">
      &larr;
    </button>
    <button id="next" data-action="slideshow#next" class="absolute right-2 top-1/2 transform -translate-y-1/2 bg-white bg-opacity-50 hover:bg-opacity-75 text-gray-800 font-bold py-2 px-4 rounded-full focus:outline-none">
      &rarr;
    </button>
  </div>

  <div id="image-modal" class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-75 hidden" data-slideshow-target="modal">
    <img src="" alt="Full Image" class="max-w-full max-h-full" data-slideshow-target="modalImage">
    <button class="absolute top-4 right-4 text-white text-3xl font-bold" data-action="click->slideshow#closeModal">&times;</button>
  </div>
</div>

<%= render 'shared/modal/image' %>

app/views/tanks/_tank_info_item.html.erb
<div class="flex-1">
  <div class="font-normal text-gray-700 dark:text-gray-400"><%= small_text %></div>
  <div class="text-2xl font-medium tracking-tight text-gray-900 dark:text-white"><%= large_text %></div>
</div>

app/views/tanks/_user_info.html.erb
<div class="flex flex-col md:flex-row items-center md:items-start md:space-x-4">
  <div class="flex-shrink-0">
    <div class="w-24 h-24 md:w-32 md:h-32 rounded-full overflow-hidden border border-gray-300">
      <% if user.avatar.attached? %>
        <%= image_tag(user.avatar, alt: "Profile Image", class: "object-cover w-full h-full") %>
      <% end %>
    </div>
  </div>

  <div class="mt-4 md:mt-0 text-center md:text-left flex-1">
    <h1 class="text-xl md:text-2xl font-semibold text-gray-800"><%= user.first_name %></h1>

    <div class="my-2 inline-block px-2 py-1 text-xs md:text-sm font-medium text-white rounded bg-blue-500">
      <%= user.level %>
    </div>

     <%= render partial: 'users/follows/follower_counts', locals: { user: user } %>
  </div>

  <div class="mt-4 md:mt-0 ml-auto">
    <%= render partial: 'users/follows/follow_button', locals: { user: user } %>
  </div>
</div>

app/views/tanks/edit.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-4xl font-semibold leading-7 text-gray-900 mb-3">Edit Tank Information</h1>

  <div class="py-4"><%= link_to "← Back to My Tanks", user_tanks_path, class: 'block w-full bg-gray-300 text-black px-4 py-2 rounded-lg hover:bg-gray-2000' %></div>

  <%= render partial: 'form', locals: { tank: @tank } %>

  <% if @tank.persisted? %>
    <div class="py-4"><%= link_to 'Add Livestock', tank_livestocks_path(@tank), class: 'block w-full bg-gray-300 text-black px-4 py-2 rounded-lg hover:bg-gray-200' %></div>
    <div class="py-4"><%= link_to 'Add Equipment', tank_equipments_path(@tank), class: 'block w-full bg-gray-300 text-black px-4 py-2 rounded-lg hover:bg-gray-200' %></div>
    <div class="py-4"><%= link_to 'Add Parameters', tank_parameters_path(@tank), class: 'block w-full bg-gray-300 text-black px-4 py-2 rounded-lg hover:bg-gray-200' %></div>
  <% end %>
</div>

app/views/tanks/index.html.erb
<div class="container mx-auto mt-8">
  <%= render partial: 'shared/components/h1', locals: { title: 'Tanks' } %>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-5" id="tanks">
    <%= render partial: 'tanks/tank', collection: @tanks, locals: { show_button: false } %>
  </div>

  <div class="flex justify-center" id="load_more_button">
    <%= render "tanks/load_more_button" %>
  </div>
</div>

app/views/tanks/index.turbo_stream.erb
<%= turbo_stream.append "tanks" do %>
  <%= render partial: "tanks/tank", collection: @tanks, locals: { show_button: false } %>
<% end %>

<%= turbo_stream.update "load_more_button" do %>
  <%= render "tanks/load_more_button" %>
<% end %>

app/views/tanks/new.html.erb
<div>
  <h1 class="text-4xl font-semibold leading-7 text-gray-900 mb-3">Add New Tank</h1>
  <%= render partial: 'form', locals: { tank: @tank } %>
</div>