config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'tanks/new'
  get 'tanks/create'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  get 'signup', to: 'email_signup#show'
  post 'signup', to: 'email_signup#create'
  get 'users/profile', to: 'users/profile#profile'
  put 'users/profile', to: 'users/profile#profile_update'
  resources :users, only: %i[edit update] do
    resources :follows, module: :users, only: %i[create destroy]
  end
  resources :tanks do
    resources :parameters, module: :tanks
    resources :equipments, module: :tanks
    resources :heaters, module: :tanks
    resources :lights, module: :tanks
    resources :pumps, module: :tanks
    resources :livestocks, module: :tanks
    resources :fish, module: :tanks
    resources :corals, module: :tanks
    resources :invertebrates, module: :tanks
    delete 'remove_image/:image_id', to: 'tanks#remove_image', as: 'remove_image'
  end
  resources :user_tanks, only: [:index]
  get 'up', to: proc { [200, {}, ['OK']] }
end

app/controllers/user_tanks_controller.rb
class UserTanksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tanks = current_user.tanks.order(created_at: :desc)
  end
end

app/views/user_tanks/index.html.erb
<div class="container mx-auto mt-8">
  <%= render partial: 'shared/components/h1', locals: { title: 'My Tanks' } %>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <%= render partial: 'tanks/tank', collection: @tanks, locals: { show_button: true } %>
    <%= link_to 'Add New Tank', new_tank_path, class: 'flex justify-center items-center max-w-sm bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out', data: { turbo_frame: '_top' } %>
  </div>
</div>